In [1]:
import pandas as pd
import numpy as np
import json
from sklearn.metrics import roc_auc_score, precision_recall_fscore_support, f1_score, average_precision_score


In [2]:
df = pd.read_csv('2008_features.csv')


In [3]:
df = df.dropna()    
df.head()


fips state winner    total    white   black   other     vetpct   medinc  \
3   56025    WY    rep  70493.0  65168.0   485.0  1913.0  12.958606  47648.0   
4   56005    WY    rep  38655.0  36497.0   201.0   896.0   9.458925  71335.0   
6   56033    WY    rep  27546.0  26222.0     0.0   343.0  16.668997  45040.0   
10  56037    WY    rep  38218.0  35381.0   193.0   777.0  12.942967  64050.0   
14  56021    WY    rep  85841.0  73949.0  2377.0  3813.0  19.152454  49748.0   

         hh ...      fpop  medage  sexrat    pop16   lfp  employed  unemprate  \
3   27359.0 ...   35413.0    36.9    99.1  55413.0  67.8      64.6        4.6   
4   13344.0 ...   18794.0    32.9   105.7  29284.0  79.8      75.9        4.4   
6   11929.0 ...   13733.0    41.9   100.6  22051.0  67.6      65.0        3.7   
10  15107.0 ...   18736.0    35.6   104.0  29371.0  73.6      70.9        3.7   
14  33640.0 ...   42641.0    36.1   101.3  66317.0  70.7      63.0        5.0   

    total_votes  dem  rep  
3         929.0  1.0  0.0  
4         180.0  1.0  0.0  
6         526.0  1.0  0.0  
10        596.0  1.0  0.0  
14       1528.0  1.0  0.0  

[5 rows x 26 columns]

In [18]:

import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns
from sklearn.cross_validation import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, mean_squared_error
from sklearn import cross_validation, datasets, grid_search
from sklearn.metrics import mean_squared_error
from sklearn.learning_curve import learning_curve
%matplotlib inline

In [19]:
df['winner'] = df['winner'].replace('rep',1).replace('dem',0)


In [20]:
df.head()


fips state  winner    total    white   black   other     vetpct   medinc  \
3   56025    WY       1  70493.0  65168.0   485.0  1913.0  12.958606  47648.0   
4   56005    WY       1  38655.0  36497.0   201.0   896.0   9.458925  71335.0   
6   56033    WY       1  27546.0  26222.0     0.0   343.0  16.668997  45040.0   
10  56037    WY       1  38218.0  35381.0   193.0   777.0  12.942967  64050.0   
14  56021    WY       1  85841.0  73949.0  2377.0  3813.0  19.152454  49748.0   

         hh ...      fpop  medage  sexrat    pop16   lfp  employed  unemprate  \
3   27359.0 ...   35413.0    36.9    99.1  55413.0  67.8      64.6        4.6   
4   13344.0 ...   18794.0    32.9   105.7  29284.0  79.8      75.9        4.4   
6   11929.0 ...   13733.0    41.9   100.6  22051.0  67.6      65.0        3.7   
10  15107.0 ...   18736.0    35.6   104.0  29371.0  73.6      70.9        3.7   
14  33640.0 ...   42641.0    36.1   101.3  66317.0  70.7      63.0        5.0   

    total_votes  dem  rep  
3         929.0  1.0  0.0  
4         180.0  1.0  0.0  
6         526.0  1.0  0.0  
10        596.0  1.0  0.0  
14       1528.0  1.0  0.0  

[5 rows x 26 columns]

In [23]:
X = df.drop(['winner','state','pop','mpop','fpop','pop16'], axis = 1)
y = df.winner

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.30)


In [24]:
nlist = []
for k in range(1, 101):
    neigh = KNeighborsClassifier(n_neighbors=k)
    neigh.fit(X_train,y_train)
    y_hat = neigh.predict(X_test)
    nlist.append([k, accuracy_score(y_test, y_hat)])
nlist

[[1, 0.77053140096618356],
 [2, 0.72705314009661837],
 [3, 0.75845410628019327],
 [4, 0.73671497584541068],
 [5, 0.74879227053140096],
 [6, 0.73913043478260865],
 [7, 0.76086956521739135],
 [8, 0.77053140096618356],
 [9, 0.75362318840579712],
 [10, 0.76328502415458932],
 [11, 0.76086956521739135],
 [12, 0.76328502415458932],
 [13, 0.7560386473429952],
 [14, 0.74879227053140096],
 [15, 0.74154589371980673],
 [16, 0.73671497584541068],
 [17, 0.73188405797101452],
 [18, 0.72946859903381644],
 [19, 0.71739130434782605],
 [20, 0.72222222222222221],
 [21, 0.71739130434782605],
 [22, 0.72222222222222221],
 [23, 0.72463768115942029],
 [24, 0.72463768115942029],
 [25, 0.71739130434782605],
 [26, 0.72463768115942029],
 [27, 0.71980676328502413],
 [28, 0.72705314009661837],
 [29, 0.72222222222222221],
 [30, 0.71980676328502413],
 [31, 0.72463768115942029],
 [32, 0.72463768115942029],
 [33, 0.72222222222222221],
 [34, 0.71980676328502413],
 [35, 0.72705314009661837],
 [36, 0.72705314009661837],
 [

In [25]:
logistic = LogisticRegression()
logistic.fit(X_train, y_train)
predicted = logistic.predict(X_test)
accuracy_score(y_test,predicted)


0.76328502415458932

In [26]:
dems = pd.Series(0,index=np.arange(len(y_test)))
accuracy_score(y_test, dems)

0.33574879227053139

In [27]:
reps = pd.Series(1, index=np.arange(len(y_test)))
accuracy_score(y_test, reps)

0.66425120772946855

In [28]:
X = df.drop(['winner','state','pop','fpop','mpop'], axis = 1)
# X = df[['rep','dem','bs25','hsg25']]
y = df.winner

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.30)

rfc = RandomForestClassifier(n_estimators=500, max_depth=6)
rfc.fit(X_train, y_train)
rf_preds = rfc.predict(X_test)
accuracy_score(y_test, rf_preds)


0.78502415458937203

In [31]:
X = df.drop(['winner','state','pop','fpop','mpop'], axis = 1)
y = df.winner

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.30)

logreg = LogisticRegression()
logreg.fit(X_train, y_train)
predictions = logreg.predict(X_test)
accuracy_score(y_test,predictions)
logreg.predict_proba(X_test)

array([[  2.11593086e-01,   7.88406914e-01],
       [  1.62123994e-01,   8.37876006e-01],
       [  2.07140953e-01,   7.92859047e-01],
       [  2.56662426e-01,   7.43337574e-01],
       [  7.93461237e-01,   2.06538763e-01],
       [  1.80701292e-01,   8.19298708e-01],
       [  5.72818426e-01,   4.27181574e-01],
       [  9.95454759e-01,   4.54524095e-03],
       [  3.63815224e-01,   6.36184776e-01],
       [  2.22924351e-01,   7.77075649e-01],
       [  1.43747426e-01,   8.56252574e-01],
       [  5.78341576e-01,   4.21658424e-01],
       [  3.10250535e-03,   9.96897495e-01],
       [  3.34905065e-01,   6.65094935e-01],
       [  1.87551497e-01,   8.12448503e-01],
       [  1.91046643e-01,   8.08953357e-01],
       [  3.09089500e-01,   6.90910500e-01],
       [  1.66675410e-01,   8.33324590e-01],
       [  4.18886584e-02,   9.58111342e-01],
       [  1.46285034e-01,   8.53714966e-01],
       [  5.09233576e-01,   4.90766424e-01],
       [  4.05703080e-01,   5.94296920e-01],
       [  

In [128]:

sorted(zip(X_train.columns,rfc.feature_importances_), key=lambda x: x[1], reverse=True)



[('rep', 0.11240812521414013),
 ('dem', 0.10307233984621371),
 ('bs25', 0.073065623222856729),
 ('hsg25', 0.067103889914510786),
 ('pop16', 0.066409555496552905),
 ('fips', 0.061181592804137923),
 ('hh', 0.059525198219193352),
 ('otherhh', 0.054478107914867867),
 ('total', 0.05093531720599246),
 ('total_votes', 0.043337494340072627),
 ('white', 0.040121039404070469),
 ('famhh', 0.036007005144027042),
 ('unemprate', 0.035980417174138482),
 ('black', 0.03028847915646769),
 ('medage', 0.029262853130755974),
 ('vetpct', 0.027559610463481904),
 ('sexrat', 0.02435721486931609),
 ('other', 0.023118733624771074),
 ('medinc', 0.022594156950941639),
 ('lfp', 0.020748823708167496),
 ('employed', 0.018444422195323554)]

In [62]:
precision_recall_fscore_support(y_test, rf_preds)


(array([ 0.80582524,  0.80064309]),
 array([ 0.57241379,  0.92565056]),
 array([ 0.66935484,  0.85862069]),
 array([145, 269]))

In [63]:
f1_score(y_test, rf_preds)


0.85862068965517235

In [64]:
average_precision_score(y_test, rf_preds)


0.88730141159074971

In [66]:
df_2016 = pd.read_csv('2016_features_2.csv')
# df_2016 = df_2016.dropna()
X_16 = df_2016.drop(['winner','state','pop','mpop','fpop'], axis = 1)
for i in X_16.columns:
    if i == 'fips':
        continue
    else:
        X_16[i] = X_16[i].fillna(X_16[i].mean())
y_16 = df_2016.winner


In [67]:
X_16['alaska'] = X_16['fips'].apply(lambda x: x.find('AK'))
X_16 = X_16[X_16['alaska'] != 0]
X_16 = X_16.drop('alaska',axis=1)



In [68]:
rf_preds_16 = rfc.predict(X_16)
rf_probs_16 = rfc.predict_proba(X_16)
zipped_16 = zip(rf_preds_16, rf_probs_16)


In [69]:
dem_prob_16 = pd.DataFrame(rf_probs_16[:,[0]])


In [70]:
zipped_results_16 = zip(df_2016['fips'],dem_prob_16[0])




In [71]:
resdict_16 = {}
for i in zipped_results_16:
    intconv = int(i[0])
    resdict_16[intconv] =i[1]
    
    
    

In [72]:
#jsond = json.dumps(resdict)
# f = open('predicted2016_2.csv','w')
# f.write(jsond)

In [73]:
len(resdict.keys())


3113

In [74]:
df_2008 = pd.read_csv('2008_features.csv')
# df_2016 = df_2016.dropna()
X_08 = df_2008.drop(['winner','state','pop','mpop','fpop'], axis = 1)
for i in X_08.columns:
    if i == 'fips':
        continue
    else:
        X_08[i] = X_08[i].fillna(X_08[i].mean())
y_08 = df_2008.winner

X_08['alaska'] = X_08['fips'].apply(lambda x: x.find('AK'))
X_08 = X_08[X_08['alaska'] != 0]
X_08 = X_08.drop('alaska',axis=1)


In [75]:
rf_preds_08 = rfc.predict(X_08)
rf_probs_08 = rfc.predict_proba(X_08)
zipped = zip(rf_preds_08, rf_probs_08)

In [76]:
dem_prob_08 = pd.DataFrame(rf_probs_08[:,[0]])
zipped_results_08 = zip(df_2008['fips'],dem_prob_08[0])


In [77]:
resdict_08 = {}
for i in zipped_results_08:
    intconv = int(i[0])
    resdict_08[intconv] =i[1]

In [78]:
ec_2008 = zip(df_2008['state'],X_08['fips'],X_08['pop16'],dem_prob_08[0])
ec_2008 = pd.DataFrame(ec_2008)
ec_2008.columns = ['state','fips','population','dems']
ec_2008['demvotes'] = ec_2008['dems']*ec_2008['population']
summed_2008 = ec_2008.groupby('state').sum()
summed_2008['dempct'] = summed_2008['demvotes']/summed_2008['population']
summed_2008['demwin'] = summed_2008['dempct'].apply(lambda x: int(x>.5))
dem_wins = summed_2008[summed_2008['demwin']==1]

In [79]:
ec_dict = {'MS':6,'AL':9,'AK':3,'AZ':11,'AR':6,'CA':55,'CO':9,'CT':7,'DE':3,'FL':29,'GA':16,'HI':4,'ID':4,'IL':20,'IN':11,'IA':6,'KS':6,'KY':8,'LA':8,'ME':4,'MD':10,'MA':11,'MI':16,'MN':10,'MS':6,'MO':10,'MT':3,'NE':5,'NV':6,'NH':4,'NJ':14,'NM':5,'NY':29,'NC':15,'ND':3,'OH':18,'OK':7,'OR':7,'PA':20,'RI':4,'SC':9,'SD':3,'TN':11,'TX':38,'UT':6,'VT':3,'VA':13,'WA':12,'WV':5,'WI':10,'WY':3,'DC':3}
predicted_ec_2008 = 0
for i in dem_wins.index:
    predicted_ec_2008+=ec_dict[i]
predicted_ec_2008

411

In [80]:
ec_2016 = zip(df_2016['state'],X_16['fips'],X_16['pop16'],dem_prob[0])
ec_2016 = pd.DataFrame(ec_2016)
ec_2016.columns = ['state','fips','population','dems']
ec_2016['demvotes'] = ec_2016['dems']*ec_2016['population']
summed_2016 = ec_2016.groupby('state').sum()
summed_2016['dempct'] = summed_2016['demvotes']/summed_2016['population']
summed_2016['demwin'] = summed_2016['dempct'].apply(lambda x: int(x >.5))
dem_wins_2016 = summed_2016[summed_2016['demwin']==1]

In [81]:
predicted_ec_2016 = 0
for i in dem_wins_2016.index:
    predicted_ec_2016+=ec_dict[i]
predicted_ec_2016





268

In [138]:
loop = 0
nloops = 100
ec_2016_predictions = []
df_2016 = pd.read_csv('2016_features_2.csv')
# df_2016 = df_2016.dropna()
X_16 = df_2016.drop(['winner','state','pop','mpop','fpop'], axis = 1)
for i in X_16.columns:
    if i == 'fips':
        continue
    else:
        X_16[i] = X_16[i].fillna(X_16[i].mean())
y_16 = df_2016.winner
ec_dict = {'MS':6,'AL':9,'AK':3,'AZ':11,'AR':6,'CA':55,'CO':9,'CT':7,'DE':3,'FL':29,'GA':16,'HI':4,'ID':4,'IL':20,'IN':11,'IA':6,'KS':6,'KY':8,'LA':8,'ME':4,'MD':10,'MA':11,'MI':16,'MN':10,'MS':6,'MO':10,'MT':3,'NE':5,'NV':6,'NH':4,'NJ':14,'NM':5,'NY':29,'NC':15,'ND':3,'OH':18,'OK':7,'OR':7,'PA':20,'RI':4,'SC':9,'SD':3,'TN':11,'TX':38,'UT':6,'VT':3,'VA':13,'WA':12,'WV':5,'WI':10,'WY':3,'DC':3}
X_16['alaska'] = X_16['fips'].apply(lambda x: x.find('AK'))
X_16 = X_16[X_16['alaska'] != 0]
X_16 = X_16.drop('alaska',axis=1)

while loop < nloops:


    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.30)

    rfc = RandomForestClassifier(n_estimators=500, max_depth=6)
    rfc.fit(X_train, y_train)
    rf_preds = rfc.predict(X_test)
    accuracy_score(y_test, rf_preds)
    rf_preds_16 = rfc.predict(X_16)
    rf_probs_16 = rfc.predict_proba(X_16)
    zipped_16 = zip(rf_preds_16, rf_probs_16)
    dem_prob_16 = pd.DataFrame(rf_probs_16[:,[0]])
    zipped_results_16 = zip(df_2016['fips'],dem_prob_16[0])
    resdict_16 = {}
    for i in zipped_results_16:
        intconv = int(i[0])
        resdict_16[intconv] =i[1]
    ec_2016 = zip(df_2016['state'],X_16['fips'],X_16['pop16'],dem_prob_16[0])
    ec_2016 = pd.DataFrame(ec_2016)
    ec_2016.columns = ['state','fips','population','dems']
    ec_2016['demvotes'] = ec_2016['dems']*ec_2016['population']
    summed_2016 = ec_2016.groupby('state').sum()
    summed_2016['dempct'] = summed_2016['demvotes']/summed_2016['population']
    summed_2016['demwin'] = summed_2016['dempct'].apply(lambda x: int(x >.5))
    dem_wins_2016 = summed_2016[summed_2016['demwin']==1]
    predicted_ec_2016 = 0
    for i in dem_wins_2016.index:
        predicted_ec_2016+=ec_dict[i]
    ec_2016_predictions.append(predicted_ec_2016)
    loop+=1
    if loop%10 == 0: print loop


10
20
30
40
50
60
70
80
90
100


In [174]:
df_2016 = pd.read_csv('2016_features_2.csv')


In [158]:

pd.DataFrame(ec_2016_predictions).describe()


0
count  100.000000
mean   315.100000
std     32.210012
min    251.000000
25%    287.750000
50%    315.000000
75%    336.000000
max    389.000000

In [183]:
df_2016_preds = pd.merge(df_2016,summed_2016.reset_index(),'left','state')[['fips','demwin']]
df_2016_preds['fips'] = df_2016_preds['fips'].apply(lambda x : int(x))
df_2016_preds.to_csv('/Users/R1/ds/metis/metis_work/d32016/ec2016_2.csv')


ValueError: invalid literal for int() with base 10: 'AKL15'

In [181]:
test = pd.merge(df_2016,summed_2016.reset_index(),'left','state')
test[test['state'] == 'CA']


fips state winner      total      white     black      other  \
2898  06115    CA    rep    73059.0    51133.0    2378.0     7472.0   
2899  06041    CA    dem   256802.0   203975.0    6913.0    19664.0   
2900  06029    CA    rep   857730.0   632452.0   48412.0    97625.0   
2901  06001    CA    dem  1559308.0   707017.0  184785.0   126476.0   
2902  06113    CA    dem   204162.0   134790.0    5314.0    21710.0   
2903  06013    CA    dem  1081232.0   671384.0   97035.0    77416.0   
2904  06027    CA    rep    18439.0    15267.0     202.0      303.0   
2905  06087    CA    dem   267203.0   215832.0    2459.0    24084.0   
2906  06005    CA    rep    37159.0    32551.0     812.0     1191.0   
2907  06081    CA    dem   739837.0   417138.0   19503.0    61897.0   
2908  06009    CA    rep    44921.0    41129.0     292.0      671.0   
2909  06107    CA    rep   451108.0   365823.0    7884.0    40340.0   
2910  06055    CA    dem   139253.0   107543.0    2992.0    12354.0   
2911  06095    CA    dem   421624.0   226669.0   59510.0    36770.0   
2912  06097    CA    dem   491790.0   387044.0    7490.0    49266.0   
2913  06045    CA    dem    87612.0    72141.0     705.0     5536.0   
2914  06105    CA    rep    13515.0    11917.0     110.0      116.0   
2915  06085    CA    dem  1841569.0   907336.0   48660.0   174427.0   
2916  06059    CA    rep  3086331.0  1942675.0   50766.0   387005.0   
2917  06031    CA    rep   151390.0   106922.0    9843.0    20287.0   
2918  06057    CA    rep    98606.0    91335.0     358.0     1632.0   
2919  06065    CA    dem  2266899.0  1480532.0  141350.0   379932.0   
2920  06023    CA    dem   134876.0   110595.0    1755.0     4218.0   
2921  06083    CA    dem   431555.0   319490.0    8471.0    58911.0   
2922  06079    CA    dem   274184.0   231961.0    5791.0    15160.0   
2923  06015    CA    rep    28066.0    21437.0    1007.0     1103.0   
2924  06063    CA    rep    19286.0    17273.0     135.0      239.0   
2925  06073    CA    dem  3183143.0  2259494.0  160316.0   215265.0   
2926  06035    CA    rep    33356.0    24131.0    2905.0     3338.0   
2927  06021    CA    rep    28019.0    23858.0     249.0     1740.0   
2928  06047    CA    dem   261609.0   168794.0    9115.0    50949.0   
2929  06111    CA    dem   835790.0   649278.0   15035.0    70998.0   
2930  06067    CA    dem  1450277.0   865905.0  146236.0   101936.0   
2931  06075    CA    dem   829072.0   410245.0   47611.0    49540.0   
2932  06093    CA    rep    44261.0    38114.0     574.0      652.0   
2933  06077    CA    dem   701050.0   405458.0   50377.0    80481.0   
2934  06019    CA    dem   948844.0   555967.0   48276.0   201491.0   
2935  06025    CA    dem   177026.0   120826.0    5205.0    37347.0   
2936  06051    CA    dem    14193.0    11993.0      63.0     1270.0   
2937  06099    CA    dem   522794.0   396628.0   14456.0    52446.0   
2938  06069    CA    dem    56888.0    48133.0     574.0     4209.0   
2939  06101    CA    rep    95067.0    65256.0    1925.0     7089.0   
2940  06033    CA    dem    64209.0    51591.0    1497.0     5999.0   
2941  06039    CA    rep   152452.0   125830.0    5382.0    10254.0   
2942  06049    CA    rep     9335.0     8396.0     108.0      131.0   
2943  06053    CA    dem   424927.0   319839.0   11826.0    44818.0   
2944  06089    CA    rep   178520.0   155559.0    1759.0     4025.0   
2945  06109    CA    rep    54347.0    47833.0    1018.0     1896.0   
2946  06017    CA    rep   181465.0   158367.0    1781.0     6368.0   
2947  06091    CA    rep     3019.0     2793.0       4.0      126.0   
2948  06003    CA    dem     1202.0      854.0      11.0       34.0   
2949  06037    CA    dem  9974203.0  5329333.0  832253.0  1949940.0   
2950  06103    CA    rep    63284.0    54972.0     315.0     3006.0   
2951  06061    CA    rep   361518.0   303509.0    4652.0    10753.0   
2952  06043    CA    rep    17946.0    15850.0     155.0      399.0   
2953  06007    CA    rep   2215

In [156]:
loop = 0
nloops = 100
ec_2008_predictions = []
df_2008 = pd.read_csv('2008_features.csv')
# df_2016 = df_2016.dropna()
X_08 = df_2008.drop(['winner','state','pop','mpop','fpop'], axis = 1)
for i in X_08.columns:
    if i == 'fips':
        continue
    else:
        X_08[i] = X_08[i].fillna(X_08[i].mean())
y_08 = df_2008.winner
ec_dict = {'MS':6,'AL':9,'AK':3,'AZ':11,'AR':6,'CA':55,'CO':9,'CT':7,'DE':3,'FL':29,'GA':16,'HI':4,'ID':4,'IL':20,'IN':11,'IA':6,'KS':6,'KY':8,'LA':8,'ME':4,'MD':10,'MA':11,'MI':16,'MN':10,'MS':6,'MO':10,'MT':3,'NE':5,'NV':6,'NH':4,'NJ':14,'NM':5,'NY':29,'NC':15,'ND':3,'OH':18,'OK':7,'OR':7,'PA':20,'RI':4,'SC':9,'SD':3,'TN':11,'TX':38,'UT':6,'VT':3,'VA':13,'WA':12,'WV':5,'WI':10,'WY':3,'DC':3}
X_08['alaska'] = X_08['fips'].apply(lambda x: x.find('AK'))
X_08 = X_08[X_08['alaska'] != 0]
X_08 = X_08.drop('alaska',axis=1)

while loop < nloops:

    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=.30)

    rfc = RandomForestClassifier(n_estimators=500, max_depth=6)
    rfc.fit(X_train, y_train)
    rf_preds = rfc.predict(X_test)
    accuracy_score(y_test, rf_preds)
    rf_preds_08 = rfc.predict(X_08)
    rf_probs_08 = rfc.predict_proba(X_08)
    zipped_08 = zip(rf_preds_08, rf_probs_08)
    dem_prob_08 = pd.DataFrame(rf_probs_08[:,[0]])
    zipped_results_08 = zip(df_2008['fips'],dem_prob_08[0])
    resdict_08 = {}
    for i in zipped_results_08:
        intconv = int(i[0])
        resdict_08[intconv] =i[1]
    ec_2008 = zip(df_2008['state'],X_08['fips'],X_08['pop16'],dem_prob_08[0])
    ec_2008 = pd.DataFrame(ec_2008)
    ec_2008.columns = ['state','fips','population','dems']
    ec_2008['demvotes'] = ec_2008['dems']*ec_2008['population']
    summed_2008 = ec_2008.groupby('state').sum()
    summed_2008['dempct'] = summed_2008['demvotes']/summed_2008['population']
    summed_2008['demwin'] = summed_2008['dempct'].apply(lambda x: int(x >.5))
    dem_wins_2008 = summed_2008[summed_2008['demwin']==1]
    predicted_ec_2008 = 0
    for i in dem_wins_2008.index:
        predicted_ec_2008+=ec_dict[i]
    ec_2008_predictions.append(predicted_ec_2008)
    loop+=1
    if loop%10 == 0: print loop

10
20
30
40
50
60
70
80
90
100


In [157]:
pd.DataFrame(ec_2008_predictions).describe()

0
count  100.000000
mean   264.650000
std     31.897365
min    200.000000
25%    240.000000
50%    266.500000
75%    286.750000
max    329.000000

In [184]:
import numpy as np
import matplotlib.pyplot as plt


def pr_curve(truthvec, scorevec):
    threshvec = np.unique(scorevec)
    numthresh = len(threshvec)
    tpvec = np.zeros(numthresh)
    fpvec = np.zeros(numthresh)
    fnvec = np.zeros(numthresh)

    for i in range(numthresh):
        thresh = threshvec[i]
        tpvec[i] = sum(truthvec[scorevec>=thresh])
        fpvec[i] = sum(1-truthvec[scorevec>=thresh])
        fnvec[i] = sum(truthvec[scorevec<thresh])
    recallvec = tpvec/(tpvec + fnvec)
    precisionvec = tpvec/(tpvec + fpvec)
    plt.plot(precisionvec,recallvec)
    plt.axis([0, 1, 0, 1])
    return (recallvec, precisionvec, threshvec)

IndexError: too many indices for array